# Check Eigen3 installation
FILE(GLOB_RECURSE EIGEN3_FOUND_CMAKE_FILE "${EIGEN3_INSTALL_PATH}/Eigen3Config.cmake")

MESSAGE(STATUS "  Eigen3 install path : ${EIGEN3_INSTALL_PATH}")
MESSAGE(STATUS "  Eigen3 found cmake config : ${EIGEN3_FOUND_CMAKE_FILE}")

IF (EIGEN3_FOUND_CMAKE_FILE)
  INCLUDE(${EIGEN3_FOUND_CMAKE_FILE})
  SET(EIGEN3_FOUND ON)
ELSE()
  MESSAGE(FATAL_ERROR "-- EIGEN3 is not found at ${EIGEN3_INSTALL_PATH}")
ENDIF()
